_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.18
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": darwin-arm64
action_dim:
    value: 4
batch_size:
    value: 1024
copy_action:
    value: false
cuda:
    value: false
dataset:
    value: modal_train/data/balls_train_500.h5
decoder:
    value: false
embedding_dim:
    value: 4
encoder:
    value: medium
epochs:
    value: 100
hidden_dim:
    value: 512
hinge:
    value: 1
ignore_action:
    value: false
learning_rate:
    value: 0.0005
log_interval:
    value: 20
model_file:
    value: models/balls_model.pt
name:
    value: balls
no_cuda:
    value: false
num_objects:
    value: 3
save_folder:
    value: models
seed:
    value: 42
sigma:
    value: 0.5
